version: '3.8'

services:
  # Backend API service for development
  backend:
    build:
      context: ./be
      dockerfile: Dockerfile
    container_name: linkedin-ads-backend-dev
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY:-}
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2:-true}
      - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT:-linkedin-ads-studio-dev}
      - FASTAPI_ENV=development
    env_file:
      - ./be/.env
    volumes:
      - ./be:/app  # Read-write for development
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    restart: unless-stopped
    networks:
      - linkedin-ads-dev-network

  # Frontend development server
  frontend:
    image: node:18-alpine
    container_name: linkedin-ads-frontend-dev
    working_dir: /app
    ports:
      - "5173:5173"  # Vite dev server port
    environment:
      - VITE_API_URL=http://localhost:8000/api/v1
    volumes:
      - ./fe:/app
      - /app/node_modules  # Anonymous volume for node_modules
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - linkedin-ads-dev-network

networks:
  linkedin-ads-dev-network:
    driver: bridge
    name: linkedin-ads-dev-network
